version: '3'
services:
  db:
    image: mysql:latest
    container_name: todo-db
    ports: 
      - 3309:3306 
    environment:
      MYSQL_ROOT_PASSWORD: bd_todo_123
      MYSQL_DATABASE: bd_todo
      MYSQL_USER: usr_todo
      MYSQL_PASSWORD: usr_todo
    volumes:
      - db-data:/var/lib/mysql
      - db-data-config:/etc/mysql
    networks:
      - mysql-python-network

  api:
    container_name: todo-api
    build:
      context: ./ToDoApi
    
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mysql-python-network

networks:
  mysql-python-network:
    name: mysql-python-network
volumes:
  db-data:
  db-data-config:
   
