# Use a imagem oficial do Nginx como base
FROM nginx:latest

# Copie os arquivos do seu projeto para o diretório de trabalho do Nginx
COPY . /usr/share/nginx/html

# Exponha a porta 80 para permitir o acesso ao servidor web
EXPOSE 80

# Comando para iniciar o servidor Nginx quando o contêiner for executado
CMD ["nginx", "-g", "daemon off;"]
